GET http://localhost:3000/articles
###
GET http://localhost:3000/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDY5MTU0MTgsImV4cCI6MTY0NjkxOTAxOH0.u7xTBjYWI5j39945NRWEgF7ZOvSDCYGRQFQ4Y4dAoSM

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "tom@email.com",
    "password": "secret123"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "tom@email.com",
    "password": "1"
}

###